# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f615d8fa83f27f8dfeda039279793a40102d46ec4e027555eb721b78d681104ddd12660a111ad123c76c552e6452a7060222c495d318eecbdfdf71e779a993b

test:
  secret_key_base: 7cf5dd1d740d32867ce7767563b7095806734a86c08e6595e13748f12dbc0a3637eddbbf8e8168de76f8a083a1560eba53fba118d0f5ec35e94a45ef1c25e781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
